// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx2a8Bd3nKktYcwEZPYipBvAhwztBxIh0',
    appId: '1:512640555749:web:321ac05e18799b6f73920c',
    messagingSenderId: '512640555749',
    projectId: 'lembufit',
    authDomain: 'lembufit.firebaseapp.com',
    databaseURL: 'https://lembufit-default-rtdb.firebaseio.com',
    storageBucket: 'lembufit.firebasestorage.app',
    measurementId: 'G-DRXB4FDLXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0G0hdMWTgbQCxIzUyNrqcOy1A78ZA8Ik',
    appId: '1:512640555749:android:074d02c539adac7473920c',
    messagingSenderId: '512640555749',
    projectId: 'lembufit',
    databaseURL: 'https://lembufit-default-rtdb.firebaseio.com',
    storageBucket: 'lembufit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClC_-FkWy8nVsmZaS4dePk3cK5uZEqvJ8',
    appId: '1:512640555749:ios:b05ff4cefc8e65ab73920c',
    messagingSenderId: '512640555749',
    projectId: 'lembufit',
    databaseURL: 'https://lembufit-default-rtdb.firebaseio.com',
    storageBucket: 'lembufit.firebasestorage.app',
    iosBundleId: 'com.example.lembufitO1',
  );
}
